### ISSUE TITLE
OPENCV 

### ISSUE THREAD

**Issue by duckscorpion13** [voarlese/auto-cloudia-pick-loop#1]
3.
OPENCV 放到在autotest 需要把opencv 的 c/c++ lib檔案build出來 詳情可以看這篇, build opencv 只需要做到第二步, 把 opencv 的 dylib 弄出來就好了, run java 時候要引入

想問問這步驟的詳細作法是什麼?

**Comment by voarlese** [comment]
github更新了  我忘記放上連結

duckscorpion13 <notifications@github.com> 於 2021年2月1日 週一 下午10:28寫道：
